print("hello word!")
num1=int(input("enter a number:"))
num2=int(input("enter another number"))
print('sum:',num1+num2)
print('difference:',num1-num2)
print('multiplication:',num1*num2)
print('Int div:',num1/num2)
print('Div:',num1/num2)
print('remainder', num1%num2)
print('power:',num1**num2)